<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
    <name>phoxi_camera_example</name>
    <version>2.0.0</version>
    <description>An example client node demonstrating how to interact with the phoxi_camera ROS 2 driver.</description>
    <author>Zebra Technologies Slovakia s.r.o</author>
    <maintainer email="support@photoneo.com">Photoneo</maintainer>
    <license>MIT</license>

    <buildtool_depend>ament_cmake</buildtool_depend>

    <depend>lifecycle_msgs</depend>
    <depend>phoxi_camera_msgs</depend>
    <depend>rclcpp</depend>
    <depend>rclcpp_components</depend>
    <depend>sensor_msgs</depend>
    <depend>std_srvs</depend>

    <exec_depend>ament_index_python</exec_depend>
    <exec_depend>launch</exec_depend>
    <exec_depend>launch_ros</exec_depend>
    <exec_depend>phoxi_camera</exec_depend>
    <exec_depend>phoxi_camera_rviz</exec_depend>
    <exec_depend>rviz2</exec_depend>
    <exec_depend>tf2_ros</exec_depend>

    <export>
        <build_type>ament_cmake</build_type>
    </export>
</package>
