<?xml version="1.0"?>
<package format="3">
    <name>phoxi_camera_rviz</name>
    <version>2.0.0</version>
    <description>RViz visualization launch files and configurations for the PhoXi camera.</description>
    <author>Zebra Technologies Slovakia s.r.o</author>
    <maintainer email="support@photoneo.com">Photoneo</maintainer>
    <license>MIT</license>

    <buildtool_depend>ament_cmake</buildtool_depend>

    <exec_depend>ament_index_python</exec_depend>
    <exec_depend>launch</exec_depend>
    <exec_depend>launch_ros</exec_depend>
    <exec_depend>phoxi_camera</exec_depend>
    <exec_depend>rviz2</exec_depend>

    <export>
        <build_type>ament_cmake</build_type>
    </export>
</package>
